name: API

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pr_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run test_user.py
        run: |
          python -m unittest discover -s src/tests -p "test_user.py" 2>  test_output.log
          if grep -i "AssertionError" test_output.log; then
            exit 1
          fi

      - name: Run test_health.py
        run: |
          python3 src/tests/test_health.py 2>  test_output.log
          if grep -i "AssertionError" test_output.log; then
            exit 1
          fi
