name: Packer Build with Application Artifact
on:
  workflow_run:
    workflows: ["API"]  
    types:
      - completed

   
jobs:
  build-and-packer-job:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Package application
        run: |
          mkdir webapp
          cp -r src webapp/
          cp app.py webapp/
          cp requirements.txt webapp/
          cp README.md webapp/
          zip -r webapp.zip webapp/

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          
          sudo apt-get update
          sudo apt-get install -y packer


      - name: Run Packer Build
        run: |
          cd packer
          packer init .
          packer build .

      - name: Configure AWS CLI for demo activities
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Instance Refresh Script
        run: |
          cd packer
          chmod +x instance_refresh.sh  
          ./instance_refresh.sh  

        
